# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Language-XSB
version:      0.14
version_from: XSB.pm
installdirs:  site
requires:
    Inline::C:                     0
    Language::Prolog::Types:       0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
